### ISSUE TITLE
[Crash] If card name with comma is in game

### ISSUE THREAD

**Issue by drptbl** [Gizeta/ShadowWatcher#1]
Application will crash if any card name contains `,` (for example `Odile, Black Swan`) because of:

 `CardData.cs`
```csharp
var info = data.Split(',');
var card = new CardData
{
    ID = int.Parse(info[0]),
    Name = info[1],
    Cost = int.Parse(info[2]),
    Amount = amount,
};
```

![debug](https://user-images.githubusercontent.com/8177587/27764373-511c7a42-5e98-11e7-82d2-57d82e9e0938.png)

Thanks,
drptbl.

**Comment by Gizeta** [comment]
Oops, I have never tested it on the English version because I always use the Chinese translations.
Thanks for your feedback.

**Comment by drptbl** [comment]
@Gizeta No worries, happy to help.
Tried to fix this myself without success :(

**Comment by Gizeta** [comment]
@drptbl Thanks anyway.
It's midnight here:sleeping:
I will fix it tomorrow if you don't work it out:smile:

**Comment by drptbl** [comment]
One of ways to fix this:
`Name = Regex.Replace(param.CardName, @"[,]", ""),`

All you have to do is to combine regex above with yours:
`Name = Regex.Replace(param.CardName, @"(\[[a-zA-Z0-9\/\-]*(rub\<[^\>]*\>)*\])", ""),`

Cheers.

**Comment by Gizeta** [comment]
I use `\t` as a delimiter to fix this.
I think it works and won't conflict with any card name.
