### ISSUE TITLE
lambda表达式无法编译

### ISSUE THREAD

**Issue by dotaevo** [Gizeta/ShadowWatcher#4]
把项目拉下来后，发现代码中存在lambda表达式，编译死活通不过啊……我用的是vs2015，项目设置没有改过，难道是需要什么特别的设置吗？求大佬解答……

**Comment by Gizeta** [comment]
如果是指 https://github.com/Gizeta/ShadowWatcher/blob/master/Observer/Contract/ReplayData.cs#L45 这种语法的话，需要支持 C# 6.0。不过 VS2015 应该是已经支持到 6.0 了。我这边是用 VS2017 开发的，语法糖用爽了都记不得哪些是旧版本不支持的特性了。

```c#
public static ReplayData Parse(string data) => new ReplayData
{
    Data = JsonMapper.ToObject(data)
};

public string Name => Data["name"].ToString();
```
等价于
```c#
public static ReplayData Parse(string data)
{
    return new ReplayData
    {
        Data = JsonMapper.ToObject(data)
    };
}

public string Name
{
    get { return Data["name"].ToString(); }
}
```
改一下应该就能编译通过
